#!/usr/bin/python3

import os
from time import sleep 


obs = """
1º Vamos criar uma pasta para guardar as fotos que iremos capturar do video.\n (script irá tentar fazer só).\n
2º Iremos querer o caminho completo do arquivo mais o nome do arquivo com extensao.
exemplo: /home/usuario/videos/ReiDoGado.mp4\n
3º Resolução do video pode pegar ao olhar as config do video. Normalmente player de videos mostram.
coloque no estilo => 1920x1080, com o x entre eles.\n
4º Quantas imagens vc quer por segundo, padrao do ffmpeg é 25.
poucas imagens o video irá parecer que esta travando, entao recomendo 15 pelo menos, mas sera muitas imagens criadas.
E com muitas imagens rodando o control + c demora para funcionar pela velocidade que estara atualizando o loop.

Tenha todas essas infos antes de proseguir, e se ja iniciou basta olhar as infos e depois responder, sem fechar o script.\n 
"""

print(obs)

class App():
    def __init__(self):
        self.newPast()

    def newPast(self):
        try:

            self.inputPasta = input("nome da pasta a ser criada, pode ser o nome do arquivo sem a extensao\n=> ").strip()
            
            if not self.inputPasta:
                print("Digite o nome do arquivo, evite caracters especiais")
            
            else:
                self.pasta = self.inputPasta.replace(" ", "")
                self.enderecoPasta = (f"$HOME/Imagens/{self.pasta}")

                self.comandoPasta = (f"mkdir -v -p {self.enderecoPasta}")

                os.system(self.comandoPasta)
                sleep(1)
                print("verifique se a pasta foi criado com sucesso")
                print()


                self.createImage()



        except KeyboardInterrupt:
            print('Saindo....')

        except Exception as e:
            print(e)
        


    def createImage(self):
        try:
            info = """
            Digite o caminho do arquivo completo mais o nome do arquivo, evite arquivos com nomes compostos para evitar erros
            exemplo: /home/USER/Videos/lua.mp4.\n
            """
            print(info)
        
            self.inputArquivo = input("caminho do arquivo\n=> ").strip()
            print()

            self.arquivo = self.inputArquivo.replace(' ', "\\ ")
            

            self.imgVideo = input("Quantas imagens por segundo vc quer que seja tirada. Padrao 25\n=> ")

            self.resolucao = input("resoluçao do video, ex: 1920x1080 pode ser obtido na descriçao dos videos\n=> ")

            self.pegarImgVideo = f"ffmpeg -i {self.arquivo} -r {self.imgVideo} -s {self.resolucao} -f  image2 {self.enderecoPasta}/tmp-%01d.jpg"
            os.system(self.pegarImgVideo)

            print()

            arqTexto = f"ls {self.enderecoPasta}/*.jpg 2>/dev/null | wc -l > {self.enderecoPasta}/info.txt"
            os.system(arqTexto)
            print()


            print(f"Passe o comando a seguir no terminal para ver a quantidade de imagens criadas:\ncat {self.enderecoPasta}/info.txt")
            print("E edite o arquivo 7wallVideo para poder setar o video no i3wm config")

        except KeyboardInterrupt:
            print("Saindo")

        except Exception as e:
            print(e)

App()
